#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local -a v
v=($(<&0))
(( $#v > 2 ))

local -a idx=({1..$#v})
local -A set=(${v:^idx})
(( $#set == $#v ))

local -i n m k
for n in $v[1,-3]; do
  for m in $v[set[$n]+1,-2]; do
    k='2020 - n - m'
    if (( $+set[$k] )); then
      print -r -- $(( n * m * k ))
      return
    fi
  done
done

exit 1
