#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local -i n m
local -A seen
while IFS= read -r n; do
  (( ! $+seen[$n] ))
  m='2020 - n'
  if (( $+seen[$m] )); then
    print -r -- $(( n * m ))
    return
  fi
  seen[$n]=
done

exit 1
